# Sunshine configuration for CachyOS Headless

# The minimum log level printed to standard out
# none=6, fatal=5, error=4, warning=3, info=2, debug=1, verbose=0
min_log_level = info

# A list of commands to be run before/after all applications.
global_prep_cmd = [{"do":"/usr/bin/xfce4-minimise-all-windows","undo":""}]

# The file where configuration for the different applications that Sunshine can run during a stream
file_apps = apps.json

# Percentage of error correcting packets per data packet
fec_percentage = 20

# Number of channels (streams) Sunshine will generate
channels = 2

# UPnP - uncomment to enable automatic port forwarding
# upnp = on
